# Generated by Django 4.2.1 on 2023-05-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_movie_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image_converted',
            field=models.ImageField(blank=True, null=True, upload_to='movie/converted/'),
        ),
    ]
